UG-996: Implement tracking
Financial-Times/n-browsable-lists pull request #11
Opened 2022-10-11 15:35 UTC by meel-io

### Description

- Sets up tracking on the demo page
- Adds `data-trackable` properties to list and articles links

### Ticket
[UG-990](https://financialtimes.atlassian.net/browse/UG-990)

### How do I test this code?

- Check out this code and run it locally
- Open the demo page on http://localhost:3000/ and open the Network tab on your DevTools
- Confirm that these events are triggered:

| Event      | Action | Payload |
| --------- | ------ | -------- |
| Click on list title | `cta:click`| `context.domPathTokens[0].data-trackable: "browsable-list-heading"`|
| Click on article headline | `cta:click`| `context.domPathTokens[0].data-trackable: "browsable-list-article"`|

### Reminder
Have you completed these common tasks? (remove those that don't apply)

- [x] **Manual Testing** checked the expected functionality
- [x] **Guidance for reviewer** communicated expected changes / behaviour, and how reviewers can test it

### How we will review this PR
Our team uses [conventional comments](https://conventionalcomments.org/) to provide feedback.

2022-10-13 10:25 UTC, leannecornish-ft requested changes
Looks great! Component and its tracking work as intended 🌟 
Obviously this is still in draft mode, but I think it's good to go - just one blocking (I think!) comment and one suggestion, which can be safely ignored if preferred 👍

2022-10-13 13:22 UTC, leannecornish-ft commented on main.js
> +			);
ahhh sorry, I didn't realise there was another pr but that makes far more sense 😂 Would it be worth changing the base of this pr to be the `build-component` branch?

2022-10-21 16:31 UTC, leannecornish-ft requested changes, later dismissed
Looks good! I _think_ there's a slight change required, according to the PR description, apologies if I've read this wrong 😅 Otherwise, all is good 🚀

2022-10-21 16:31 UTC, leannecornish-ft commented on BrowsableListsContent.jsx
> +						<li key={id} className='browsable-lists-list-item' data-trackable="browsable-list-article"><a href={`https://www.ft.com/content/${article.id}`}>{article.title}</a></li>
Blocking question: did you mean to put this in the link rather than the list item? As this shows up in `context.domPathTokens[1]` rather than `[0]`

2022-10-24 08:45 UTC, jenniferemshepherd approved these changes
The number of `sorry`s on this PR is large 😂

2022-10-24 09:06 UTC, merged